### ISSUE TITLE
[Avatars Everywhere] Compact mode avatars don't work

### ISSUE THREAD

**Issue by BLANK-TH** [abUwUser/BDPlugins#2]
Avatars simply don't show up in compact mode even with the option enabled:
![](https://pomf.blankdvth.com/v5lm1gjheo7a.png)

**Comment by abUwUser** [comment]
Thanks for the issue! I have a messy way to identify when it should apply, so yeah, gonna fix as soon as i can!

**Comment by abUwUser** [comment]
Actually Discord changed some of their workarrounds, and so I had to do some weird stuff to make it working. Gonna push the update in some minutes!

**Comment by abUwUser** [comment]
I've fixed it, and now an update is currently being pushed

**Comment by BLANK-TH** [comment]
Doesn't look like the compiled branch that BD pulls from got updated?
